# Generated by Django 4.2.7 on 2026-03-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DropoutPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=10)),
                ('family_size', models.CharField(max_length=10)),
                ('parental_status', models.CharField(max_length=20)),
                ('mother_education', models.IntegerField()),
                ('father_education', models.IntegerField()),
                ('mother_job', models.CharField(max_length=50)),
                ('father_job', models.CharField(max_length=50)),
                ('grade_1', models.IntegerField()),
                ('grade_2', models.IntegerField()),
                ('final_grade', models.IntegerField()),
                ('number_of_failures', models.IntegerField()),
                ('number_of_absences', models.IntegerField()),
                ('study_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('wants_higher_education', models.CharField(max_length=10)),
                ('internet_access', models.CharField(max_length=10)),
                ('in_relationship', models.CharField(max_length=10)),
                ('health_status', models.IntegerField()),
                ('weekend_alcohol_consumption', models.IntegerField()),
                ('weekday_alcohol_consumption', models.IntegerField()),
                ('free_time', models.IntegerField()),
                ('going_out', models.IntegerField()),
                ('family_relationship', models.IntegerField()),
                ('school_support', models.CharField(max_length=10)),
                ('family_support', models.CharField(max_length=10)),
                ('dropout_risk_percentage', models.FloatField(default=0.0)),
                ('predicted_dropout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropout_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
