# Generated by Django 6.0.3 on 2026-03-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoutprediction',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dropoutprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
