# Generated by Django 4.2.7 on 2026-03-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dropoutprediction_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropoutprediction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
